version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${VOLUME_PATH}:/var/lib/postgresql/data
    container_name: db_cross

volumes:
  db:
